'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace car1
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: Monday, 14 April 2014 09:11.
    'Build:1.0.61214.0769
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0769"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute(),  _
     System.Diagnostics.DebuggerDisplayAttribute("Count={Count}"),  _
     System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.CollectionTypeConverter))>  _
    Partial Public Class BranchCollection
        Implements System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList(Of car1.Branch), System.Collections.Generic.ICollection(Of car1.Branch), System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
        
        Private _raisePropertyChangedEvents As Boolean = true
        
        Private _raiseCollectionChangedEvents As Boolean = true
        
        <System.NonSerializedAttribute()>  _
        Private _baseList As System.Collections.Generic.List(Of car1.Branch) = New System.Collections.Generic.List(Of car1.Branch)()
        
        <System.NonSerializedAttribute()>  _
        Private _baseTable As System.Collections.Generic.Dictionary(Of String, car1.Branch) = New System.Collections.Generic.Dictionary(Of String, car1.Branch)()
        
        <System.NonSerializedAttribute()>  _
        Private _relations As System.Collections.Hashtable = New System.Collections.Hashtable()
        
        Private _maxCount As Integer = 2147483647
        
        <System.NonSerializedAttribute()>  _
        Private _branchesCityCity As car1.City
        
        <System.NonSerializedAttribute()>  _
        Private _addNewPos As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _blm2008035919 As CodeFluent.Runtime.Utilities.BindingListManager(Of car1.Branch)
        
        Private _raiseListChangedEvents As Boolean = true
        
Public Event CollectionChanged As System.ComponentModel.CollectionChangeEventHandler Implements CodeFluent.Runtime.ICodeFluentSet.CollectionChanged
Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
Private Event System_Collections_Specialized_INotifyCollectionChanged_CollectionChanged As System.Collections.Specialized.NotifyCollectionChangedEventHandler Implements System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged
        Private _h2943838991 As Object
        
        Public Sub New()
            MyBase.New
            Me._blm2008035919 = New CodeFluent.Runtime.Utilities.BindingListManager(Of car1.Branch)(Me)
        End Sub
        
        Public Sub New(ByVal branchesCityCity As car1.City)
            MyBase.New
            Me._blm2008035919 = New CodeFluent.Runtime.Utilities.BindingListManager(Of car1.Branch)(Me)
            Me._branchesCityCity = branchesCityCity
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Overridable Property RaisePropertyChangedEvents() As Boolean
            Get
                Return Me._raisePropertyChangedEvents
            End Get
            Set
                Me._raisePropertyChangedEvents = value
            End Set
        End Property
        
        Public Overridable Property RaiseCollectionChangedEvents() As Boolean
            Get
                Return Me._raiseCollectionChangedEvents
            End Get
            Set
                Me._raiseCollectionChangedEvents = value
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Protected ReadOnly Property BaseList() As System.Collections.Generic.List(Of car1.Branch)
            Get
                Return Me._baseList
            End Get
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Protected ReadOnly Property BaseTable() As System.Collections.Generic.Dictionary(Of String, car1.Branch)
            Get
                Return Me._baseTable
            End Get
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ReadOnly Property Relations() As System.Collections.IDictionary Implements CodeFluent.Runtime.ICodeFluentSet.Relations
            Get
                Return Me._relations
            End Get
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false)>  _
        Public Overridable Property MaxCount() As Integer
            Get
                Return Me._maxCount
            End Get
            Set
                Me._maxCount = value
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ReadOnly Property BranchesCityCity() As car1.City
            Get
                Return Me._branchesCityCity
            End Get
        End Property
        
        Public Overloads Default Property Item(ByVal index As Integer) As car1.Branch Implements System.Collections.Generic.IList(Of car1.Branch).Item
            Get
                Return CType(Me.BaseList(index),car1.Branch)
            End Get
            Set
                Me.BaseList(index) = value
            End Set
        End Property
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Property System_Collections_IList_Item(ByVal index As Integer) As Object Implements System.Collections.IList.Item
            Get
                Dim i As Object = Me.BaseList(index)
                Return i
            End Get
            Set
                Me.BaseList(index) = CType(value,car1.Branch)
            End Set
        End Property
        
        Public Overloads Default Property Item(ByVal name As String) As car1.Branch
            Get
                If (name Is CType(Nothing, String)) Then
                    Throw New System.ArgumentNullException("name")
                End If
                Dim i As car1.Branch = Me.TryGetValue(name)
                Return i
            End Get
            Set
                If (name Is CType(Nothing, String)) Then
                    Throw New System.ArgumentNullException("name")
                End If
                If (value Is Nothing) Then
                    Dim branch As car1.Branch = Me.TryGetValue(name)
                    If (Not (branch) Is Nothing) Then
                        Me.Remove(branch)
                    End If
                    Return
                End If
                Dim existing As car1.Branch = Me.TryGetValue(value.Name)
                If (Not (existing) Is Nothing) Then
                    Me.Remove(existing)
                End If
                Me.Add(value)
            End Set
        End Property
        
        Public Overridable ReadOnly Property Count() As Integer Implements System.Collections.Generic.ICollection(Of car1.Branch).Count
            Get
                Dim v As Integer = CType(Me.BaseList,System.Collections.IList).Count
                Return v
            End Get
        End Property
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        ReadOnly Property System_Collections_ICollection_Count() As Integer Implements System.Collections.ICollection.Count
            Get
                Dim v As Integer = Me.Count
                Return v
            End Get
        End Property
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        ReadOnly Property CodeFluent_Runtime_ICodeFluentSet_Count() As Integer Implements CodeFluent.Runtime.ICodeFluentSet.Count
            Get
                Dim v As Integer = Me.Count
                Return v
            End Get
        End Property
        
        Public Overridable ReadOnly Property IsSynchronized() As Boolean
            Get
                Dim v As Boolean = CType(Me.BaseList,System.Collections.IList).IsSynchronized
                Return v
            End Get
        End Property
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        ReadOnly Property System_Collections_ICollection_IsSynchronized() As Boolean Implements System.Collections.ICollection.IsSynchronized
            Get
                Dim v As Boolean = Me.IsSynchronized
                Return v
            End Get
        End Property
        
        Public Overridable ReadOnly Property SyncRoot() As Object
            Get
                Dim v As Object = CType(Me.BaseList,System.Collections.IList).SyncRoot
                Return v
            End Get
        End Property
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        ReadOnly Property System_Collections_ICollection_SyncRoot() As Object Implements System.Collections.ICollection.SyncRoot
            Get
                Dim v As Object = Me.SyncRoot
                Return v
            End Get
        End Property
        
        Public Overridable ReadOnly Property IsFixedSize() As Boolean
            Get
                Dim v As Boolean = CType(Me.BaseList,System.Collections.IList).IsFixedSize
                Return v
            End Get
        End Property
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        ReadOnly Property System_Collections_IList_IsFixedSize() As Boolean Implements System.Collections.IList.IsFixedSize
            Get
                Dim v As Boolean = Me.IsFixedSize
                Return v
            End Get
        End Property
        
        Public Overridable ReadOnly Property IsReadOnly() As Boolean Implements System.Collections.Generic.ICollection(Of car1.Branch).IsReadOnly
            Get
                Dim v As Boolean = CType(Me.BaseList,System.Collections.IList).IsReadOnly
                Return v
            End Get
        End Property
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        ReadOnly Property System_Collections_IList_IsReadOnly() As Boolean Implements System.Collections.IList.IsReadOnly
            Get
                Dim v As Boolean = Me.IsReadOnly
                Return v
            End Get
        End Property
        
        Public Overridable Property RaiseListChangedEvents() As Boolean
            Get
                Return Me._raiseListChangedEvents
            End Get
            Set
                Me._raiseListChangedEvents = value
            End Set
        End Property
        
        Private ReadOnly Property AllowEdit() As Boolean Implements System.ComponentModel.IBindingList.AllowEdit
            Get
                Return Me._blm2008035919.AllowEdit
            End Get
        End Property
        
        Private ReadOnly Property AllowNew() As Boolean Implements System.ComponentModel.IBindingList.AllowNew
            Get
                Return Me._blm2008035919.AllowNew
            End Get
        End Property
        
        Private ReadOnly Property AllowRemove() As Boolean Implements System.ComponentModel.IBindingList.AllowRemove
            Get
                Return Me._blm2008035919.AllowRemove
            End Get
        End Property
        
        Private ReadOnly Property IsSorted() As Boolean Implements System.ComponentModel.IBindingList.IsSorted
            Get
                Return Me._blm2008035919.IsSorted
            End Get
        End Property
        
        Private ReadOnly Property SortDirection() As System.ComponentModel.ListSortDirection Implements System.ComponentModel.IBindingList.SortDirection
            Get
                Return Me._blm2008035919.SortDirection
            End Get
        End Property
        
        Private ReadOnly Property SortProperty() As System.ComponentModel.PropertyDescriptor Implements System.ComponentModel.IBindingList.SortProperty
            Get
                Return Me._blm2008035919.SortProperty
            End Get
        End Property
        
        Private ReadOnly Property SupportsChangeNotification() As Boolean Implements System.ComponentModel.IBindingList.SupportsChangeNotification
            Get
                Return true
            End Get
        End Property
        
        Private ReadOnly Property SupportsSearching() As Boolean Implements System.ComponentModel.IBindingList.SupportsSearching
            Get
                Return Me._blm2008035919.SupportsSearching
            End Get
        End Property
        
        Private ReadOnly Property SupportsSorting() As Boolean Implements System.ComponentModel.IBindingList.SupportsSorting
            Get
                Return Me._blm2008035919.SupportsSorting
            End Get
        End Property
        
        Private ReadOnly Property RaisesItemChangedEvents() As Boolean Implements System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
            Get
                Return Me.RaiseListChangedEvents
            End Get
        End Property
        
        Public Event AddingNew As System.ComponentModel.AddingNewEventHandler
        
        Public Event ListChanged As System.ComponentModel.ListChangedEventHandler Implements System.ComponentModel.IBindingList.ListChanged
        
        Protected Overridable Sub OnPropertyChanged(ByVal e As System.ComponentModel.PropertyChangedEventArgs)
            If (Me.RaisePropertyChangedEvents = false) Then
                Return
            End If
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, e)
            End If
        End Sub
        
        Protected Overridable Sub OnCollectionChanged(ByVal e As System.ComponentModel.CollectionChangeEventArgs)
            If (Me.RaiseCollectionChangedEvents = false) Then
                Return
            End If
            If (Not (Me.CollectionChangedEvent) Is Nothing) Then
                RaiseEvent CollectionChanged(Me, e)
            End If
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(Me, e, Me._h2943838991)
            Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Count"))
            Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Item[]"))
        End Sub
        
        Protected Overridable Sub Relate(ByVal item As car1.Branch, ByVal relationType As CodeFluent.Runtime.CodeFluentRelationType)
            CType(Me,CodeFluent.Runtime.ICodeFluentSet).Relations(item) = relationType
        End Sub
        
        Public Function Add(ByVal branch As car1.Branch) As Integer
            Dim localAdd As Integer = Me.BaseList.Count
            Me.BaseAdd(branch)
            Return localAdd
        End Function
        
        Protected Overridable Function BaseAdd(ByVal branch As car1.Branch) As Integer
            If (branch Is Nothing) Then
                Throw New System.ArgumentNullException("branch")
            End If
            If (branch.Id = -1) Then
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "branch", "car1.Branch")
            End If
            Try 
                Me.BaseTable.Add(branch.Name, branch)
            Catch ane As System.ArgumentNullException
                Throw New System.ArgumentNullException(car1.Resources.Manager.GetUserMessage(Nothing, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "car1.BranchCollection", branch.EntityKey), ane)
            Catch ae As System.ArgumentException
                Throw New System.ArgumentException(car1.Resources.Manager.GetUserMessage(Nothing, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "car1.BranchCollection", branch.Name), ae)
            End Try
            AddHandler branch.KeyChanged, AddressOf Me.OnItemKeyChanged
            If (Not (Me._branchesCityCity) Is Nothing) Then
                branch.City = Me._branchesCityCity
            End If
            Dim localAdd As Integer = Me.BaseList.Count
            Me.BaseList.Add(branch)
            Me.OnCollectionChanged(New CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, branch, localAdd))
            Me.OnListChanged(New System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd))
            Return localAdd
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Function System_Collections_IList_Add(ByVal value As Object) As Integer Implements System.Collections.IList.Add
            Dim branch As car1.Branch = Nothing
            Try 
                branch = CType(value,car1.Branch)
            Catch icex As System.InvalidCastException
                branch = Nothing
                Dim key As String = Nothing
                Try 
                    key = CType(value,String)
                    Dim count As Integer = Me.Count
                    If (Not (Me.AddByEntityKey(key)) Is Nothing) Then
                        Return 1
                    End If
                    Return 0
                Catch icex1 As System.InvalidCastException
                    key = Nothing
                End Try
                If (key Is Nothing) Then
                    Throw New System.ArgumentException("value")
                End If
            End Try
            If (branch Is Nothing) Then
                Throw New System.ArgumentException("value")
            End If
            Dim localAdd As Integer = Me.Add(branch)
            Return localAdd
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub System_Collections_Generic_ICollection_car1_Branch__Add(ByVal branch As car1.Branch) Implements System.Collections.Generic.ICollection(Of car1.Branch).Add
            Me.BaseAdd(branch)
        End Sub
        
        Public Overridable Function AddByEntityKey(ByVal key As String) As car1.Branch
            Dim branch As car1.Branch = car1.Branch.LoadByEntityKey(key)
            If ((Not (branch) Is Nothing)  _
                        AndAlso (Me.Contains(branch) = false)) Then
                Me.Add(branch)
            End If
            Return branch
        End Function
        
        Public Overloads Sub Sort()
            Me.Sort(Nothing)
        End Sub
        
        Public Overloads Overridable Sub Sort(ByVal comparer As System.Collections.Generic.IComparer(Of car1.Branch))
            Me.BaseList.Sort(comparer)
        End Sub
        
        Public Overloads Sub CopyTo(ByVal array() As car1.Branch, ByVal index As Integer) Implements System.Collections.Generic.ICollection(Of car1.Branch).CopyTo
            Me.BaseCopyTo(array, index)
        End Sub
        
        Protected Overridable Sub BaseCopyTo(ByVal array() As car1.Branch, ByVal index As Integer)
            Me.BaseList.CopyTo(array, index)
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub System_Collections_ICollection_CopyTo(ByVal array As System.Array, ByVal index As Integer) Implements System.Collections.ICollection.CopyTo
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(Me, array, index)
        End Sub
        
        Public Function Contains(ByVal branch As car1.Branch) As Boolean Implements System.Collections.Generic.ICollection(Of car1.Branch).Contains
            Dim localContains As Boolean = Me.BaseContains(branch)
            Return localContains
        End Function
        
        Protected Overridable Function BaseContains(ByVal branch As car1.Branch) As Boolean
            If (branch Is Nothing) Then
                Return false
            End If
            Dim localContains As Boolean = Me.BaseTable.ContainsKey(branch.Name)
            Return localContains
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Function System_Collections_IList_Contains(ByVal value As Object) As Boolean Implements System.Collections.IList.Contains
            Dim branch As car1.Branch
            Try 
                branch = CType(value,car1.Branch)
            Catch icex As System.InvalidCastException
                branch = Nothing
            End Try
            Return Me.Contains(branch)
        End Function
        
        Public Function IndexOf(ByVal branch As car1.Branch) As Integer Implements System.Collections.Generic.IList(Of car1.Branch).IndexOf
            Dim localIndexOf As Integer = Me.BaseIndexOf(branch)
            Return localIndexOf
        End Function
        
        Protected Overridable Function BaseIndexOf(ByVal branch As car1.Branch) As Integer
            If (branch Is Nothing) Then
                Return -1
            End If
            Dim localIndexOf As Integer = Me.BaseList.IndexOf(branch)
            Return localIndexOf
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Function System_Collections_IList_IndexOf(ByVal value As Object) As Integer Implements System.Collections.IList.IndexOf
            Dim branch As car1.Branch
            Try 
                branch = CType(value,car1.Branch)
            Catch icex As System.InvalidCastException
                branch = Nothing
            End Try
            Return Me.IndexOf(branch)
        End Function
        
        Public Overloads Sub Insert(ByVal index As Integer, ByVal branch As car1.Branch) Implements System.Collections.Generic.IList(Of car1.Branch).Insert
            Me.BaseInsert(index, branch)
        End Sub
        
        Protected Overridable Sub BaseInsert(ByVal index As Integer, ByVal branch As car1.Branch)
            If (branch Is Nothing) Then
                Throw New System.ArgumentNullException("branch")
            End If
            Try 
                Me.BaseTable.Add(branch.Name, branch)
            Catch ane As System.ArgumentNullException
                Throw New System.ArgumentNullException(car1.Resources.Manager.GetUserMessage(Nothing, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "car1.BranchCollection", branch.EntityKey), ane)
            Catch ae As System.ArgumentException
                Throw New System.ArgumentException(car1.Resources.Manager.GetUserMessage(Nothing, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "car1.BranchCollection", branch.Name), ae)
            End Try
            Me.BaseList.Insert(index, branch)
            If (Not (Me._branchesCityCity) Is Nothing) Then
                branch.City = Me._branchesCityCity
            End If
            Me.OnCollectionChanged(New CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, branch, index))
            Me.OnListChanged(New System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index))
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub System_Collections_IList_Insert(ByVal index As Integer, ByVal value As Object) Implements System.Collections.IList.Insert
            Dim branch As car1.Branch
            Try 
                branch = CType(value,car1.Branch)
            Catch icex As System.InvalidCastException
                branch = Nothing
            End Try
            Me.Insert(index, branch)
        End Sub
        
        Public Overridable Sub Clear() Implements System.Collections.Generic.ICollection(Of car1.Branch).Clear
            Dim index As Integer
            Dim count As Integer = Me.Count
            index = 0
            Do While (index < count)
                Dim Branch As car1.Branch = Me(0)
                Me.BaseRemove(Branch)
                index = (index + 1)
            Loop
            Me.OnCollectionChanged(New CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, Nothing))
            Me.OnListChanged(New System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1))
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub System_Collections_IList_Clear() Implements System.Collections.IList.Clear
            Me.Clear
        End Sub
        
        Public Function Remove(ByVal branch As car1.Branch) As Boolean Implements System.Collections.Generic.ICollection(Of car1.Branch).Remove
            Return Me.BaseRemove(branch)
        End Function
        
        Protected Overridable Function BaseRemove(ByVal branch As car1.Branch) As Boolean
            If (branch Is Nothing) Then
                Throw New System.ArgumentNullException("branch")
            End If
            Dim index As Integer = Me.IndexOf(branch)
            Me.OnListChanged(New System.ComponentModel.ListChangedEventArgs(CType(CodeFluent.Runtime.Utilities.SortableBindingList(Of car1.Branch).ListChangedTypeDeleting,System.ComponentModel.ListChangedType), index))
            Dim ret As Boolean
            ret = Me.BaseList.Remove(branch)
            RemoveHandler branch.KeyChanged, AddressOf Me.OnItemKeyChanged
            ret = Me.BaseTable.Remove(branch.Name)
            If (Not (Me._branchesCityCity) Is Nothing) Then
                branch.City = Nothing
            End If
            Me.OnCollectionChanged(New CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, branch, index))
            Me.OnListChanged(New System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index))
            Return ret
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub System_Collections_IList_Remove(ByVal value As Object) Implements System.Collections.IList.Remove
            Dim branch As car1.Branch
            Try 
                branch = CType(value,car1.Branch)
            Catch icex As System.InvalidCastException
                branch = Nothing
            End Try
            Me.Remove(branch)
        End Sub
        
        Public Overridable Sub RemoveAt(ByVal index As Integer) Implements System.Collections.Generic.IList(Of car1.Branch).RemoveAt
            Me.OnListChanged(New System.ComponentModel.ListChangedEventArgs(CType(CodeFluent.Runtime.Utilities.SortableBindingList(Of car1.Branch).ListChangedTypeDeleting,System.ComponentModel.ListChangedType), index))
            Dim branch As car1.Branch = Me.BaseList(index)
            If (Not (branch) Is Nothing) Then
                RemoveHandler branch.KeyChanged, AddressOf Me.OnItemKeyChanged
                Me.BaseTable.Remove(branch.Name)
            End If
            If (Not (Me._branchesCityCity) Is Nothing) Then
                branch.City = Nothing
            End If
            Me.BaseList.RemoveAt(index)
            Me.OnCollectionChanged(New CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, branch, index))
            Me.OnListChanged(New System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index))
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub System_Collections_IList_RemoveAt(ByVal index As Integer) Implements System.Collections.IList.RemoveAt
            Me.RemoveAt(index)
        End Sub
        
        Public Overridable Function GetEnumerator() As System.Collections.Generic.IEnumerator(Of car1.Branch) Implements System.Collections.Generic.IEnumerable(Of car1.Branch).GetEnumerator
            Dim e As System.Collections.Generic.IEnumerator(Of car1.Branch) = Me.BaseList.GetEnumerator
            Return e
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Function System_Collections_IEnumerable_GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.BaseList.GetEnumerator
        End Function
        
        Private Function TryGetValue(ByVal key As String) As car1.Branch
            Dim branch As car1.Branch = Nothing
            If (Me.BaseTable.TryGetValue(key, branch) = true) Then
                Return branch
            End If
            Return Nothing
        End Function
        
        Public Overridable Sub SaveAll()
            Dim index As Integer
            index = (Me.Count - 1)
            Do While (index >= 0)
                Dim branch As car1.Branch = Me(index)
                branch.Save
                If (branch.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted) Then
                    Me.Remove(branch)
                End If
                index = (index - 1)
            Loop
        End Sub
        
        Private Overloads Sub LoadAll(ByVal pageIndex As Integer, ByVal pageSize As Integer, ByVal pageOptions As CodeFluent.Runtime.PageOptions, ByVal reader As System.Data.IDataReader)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (pageIndex < 0) Then
                pageIndex = 0
            End If
            If (pageSize < 0) Then
                If (Not (pageOptions) Is Nothing) Then
                    pageSize = pageOptions.DefaultPageSize
                Else
                    pageSize = Integer.MaxValue
                End If
            End If
            Me._branchesCityCity = Nothing
            Me.BaseList.Clear
            Me.BaseTable.Clear
            Dim count As Integer = 0
            Dim readCount As Integer = 0
            Dim readerRead As Boolean
            readerRead = reader.Read
            Do While ((readerRead = true)  _
                        AndAlso ((count < Me.MaxCount)  _
                        AndAlso (count < pageSize)))
                readCount = (readCount + 1)
                If (CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) = true) Then
                    Dim branch As car1.Branch = New car1.Branch()
                    CType(branch,CodeFluent.Runtime.ICodeFluentEntity).ReadRecord(reader)
                    If (Me.BaseContains(branch) = false) Then
                        Me.BaseAdd(branch)
                        count = (count + 1)
                    End If
                    branch.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                End If
                readerRead = reader.Read
            Loop
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Shared Function PageLoadAll(ByVal pageIndex As Integer, ByVal pageSize As Integer, ByVal pageOptions As CodeFluent.Runtime.PageOptions) As car1.BranchCollection
            If (pageIndex < 0) Then
                pageIndex = 0
            End If
            If (pageSize < 0) Then
                If (Not (pageOptions) Is Nothing) Then
                    pageSize = pageOptions.DefaultPageSize
                Else
                    pageSize = Integer.MaxValue
                End If
            End If
            Dim ret As car1.BranchCollection = New car1.BranchCollection()
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = car1.BranchCollection.PageDataLoadAll(pageOptions)
                If (reader Is Nothing) Then
                    Return ret
                End If
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(car1.Constants.car1StoreName)
            End Try
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Shared Function LoadAll() As car1.BranchCollection
            Dim ret As car1.BranchCollection = car1.BranchCollection.PageLoadAll(Integer.MinValue, Integer.MaxValue, Nothing)
            Return ret
        End Function
        
        Public Shared Function PageDataLoadAll(ByVal pageOptions As CodeFluent.Runtime.PageOptions) As System.Data.IDataReader
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "Branch", "LoadAll")
            If (Not (pageOptions) Is Nothing) Then
                Dim enumerator As System.Collections.IEnumerator = pageOptions.OrderByArguments.GetEnumerator
                Dim b As Boolean
                Dim index As Integer = 0
                b = enumerator.MoveNext
                Do While b
                    Dim argument As CodeFluent.Runtime.OrderByArgument = CType(enumerator.Current,CodeFluent.Runtime.OrderByArgument)
                    persistence.AddParameter(String.Format("@_orderBy{0}", index), argument.Name)
                    persistence.AddParameter(String.Format("@_orderByDirection{0}", index), CType(argument.Direction,Integer))
                    index = (index + 1)
                    b = enumerator.MoveNext
                Loop
            End If
            Dim reader As System.Data.IDataReader = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence.ExecuteReader
            Return reader
        End Function
        
        Public Shared Function DataLoadAll() As System.Data.IDataReader
            Dim reader As System.Data.IDataReader = car1.BranchCollection.PageDataLoadAll(Nothing)
            Return reader
        End Function
        
        Private Overloads Sub LoadByCity(ByVal pageIndex As Integer, ByVal pageSize As Integer, ByVal pageOptions As CodeFluent.Runtime.PageOptions, ByVal reader As System.Data.IDataReader, ByVal city As car1.City)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (pageIndex < 0) Then
                pageIndex = 0
            End If
            If (pageSize < 0) Then
                If (Not (pageOptions) Is Nothing) Then
                    pageSize = pageOptions.DefaultPageSize
                Else
                    pageSize = Integer.MaxValue
                End If
            End If
            Dim cityState As CodeFluent.Runtime.CodeFluentEntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
            If (Not (city) Is Nothing) Then
                cityState = city.EntityState
            End If
            Me._branchesCityCity = city
            Me.BaseList.Clear
            Me.BaseTable.Clear
            Dim count As Integer = 0
            Dim readCount As Integer = 0
            Dim readerRead As Boolean
            readerRead = reader.Read
            Do While ((readerRead = true)  _
                        AndAlso ((count < Me.MaxCount)  _
                        AndAlso (count < pageSize)))
                readCount = (readCount + 1)
                If (CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) = true) Then
                    Dim branch As car1.Branch = New car1.Branch()
                    CType(branch,CodeFluent.Runtime.ICodeFluentEntity).ReadRecord(reader)
                    If (Me.BaseContains(branch) = false) Then
                        Me.BaseAdd(branch)
                        count = (count + 1)
                    End If
                    branch.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                End If
                readerRead = reader.Read
            Loop
            If (Not (city) Is Nothing) Then
                city.EntityState = cityState
            End If
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Shared Function PageLoadByCity(ByVal pageIndex As Integer, ByVal pageSize As Integer, ByVal pageOptions As CodeFluent.Runtime.PageOptions, ByVal city As car1.City) As car1.BranchCollection
            If (pageIndex < 0) Then
                pageIndex = 0
            End If
            If (pageSize < 0) Then
                If (Not (pageOptions) Is Nothing) Then
                    pageSize = pageOptions.DefaultPageSize
                Else
                    pageSize = Integer.MaxValue
                End If
            End If
            Dim ret As car1.BranchCollection = New car1.BranchCollection()
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = car1.BranchCollection.PageDataLoadByCity(pageOptions, city)
                If (reader Is Nothing) Then
                    Return ret
                End If
                ret.LoadByCity(pageIndex, pageSize, pageOptions, reader, city)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(car1.Constants.car1StoreName)
            End Try
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Shared Function LoadByCity(ByVal city As car1.City) As car1.BranchCollection
            Dim ret As car1.BranchCollection = car1.BranchCollection.PageLoadByCity(Integer.MinValue, Integer.MaxValue, Nothing, city)
            Return ret
        End Function
        
        Public Shared Function PageDataLoadByCity(ByVal pageOptions As CodeFluent.Runtime.PageOptions, ByVal city As car1.City) As System.Data.IDataReader
            If (city Is Nothing) Then
                Return Nothing
            End If
            If (city.Id = -1) Then
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "city", "car1.City")
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "Branch", "LoadByCity")
            persistence.AddParameter("@CityId", city.Id, CType(-1,Integer))
            If (Not (pageOptions) Is Nothing) Then
                Dim enumerator As System.Collections.IEnumerator = pageOptions.OrderByArguments.GetEnumerator
                Dim b As Boolean
                Dim index As Integer = 0
                b = enumerator.MoveNext
                Do While b
                    Dim argument As CodeFluent.Runtime.OrderByArgument = CType(enumerator.Current,CodeFluent.Runtime.OrderByArgument)
                    persistence.AddParameter(String.Format("@_orderBy{0}", index), argument.Name)
                    persistence.AddParameter(String.Format("@_orderByDirection{0}", index), CType(argument.Direction,Integer))
                    index = (index + 1)
                    b = enumerator.MoveNext
                Loop
            End If
            Dim reader As System.Data.IDataReader = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence.ExecuteReader
            Return reader
        End Function
        
        Public Shared Function DataLoadByCity(ByVal city As car1.City) As System.Data.IDataReader
            Dim reader As System.Data.IDataReader = car1.BranchCollection.PageDataLoadByCity(Nothing, city)
            Return reader
        End Function
        
        Protected Overridable Sub BaseTrace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter)
            writer.Write("[")
            writer.Write(String.Concat("Count=", Me.Count))
            writer.Write("]")
        End Sub
        
        Public Function Trace() As String
            Dim stringBuilder As System.Text.StringBuilder = New System.Text.StringBuilder()
            Dim stringWriter As System.IO.StringWriter = New System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture)
            Dim writer As System.CodeDom.Compiler.IndentedTextWriter = New System.CodeDom.Compiler.IndentedTextWriter(stringWriter)
            Me.BaseTrace(writer)
            writer.Flush
            CType(writer,System.IDisposable).Dispose
            CType(stringWriter,System.IDisposable).Dispose
            Dim sr As String = stringBuilder.ToString
            Return sr
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub CodeFluent_Runtime_ICodeFluentObject_Trace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter) Implements CodeFluent.Runtime.ICodeFluentObject.Trace
            Me.BaseTrace(writer)
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal collection As car1.BranchCollection, ByVal deep As Boolean)
            If (GetType(System.ICloneable).IsAssignableFrom(GetType(car1.Branch)) = false) Then
                deep = false
            End If
            Dim enumerator As System.Collections.Generic.IEnumerator(Of car1.Branch) = Me.GetEnumerator
            Dim b As Boolean
            b = enumerator.MoveNext
            Do While b
                If (deep = true) Then
                    collection.Add(CType(CType(enumerator.Current,System.ICloneable).Clone,car1.Branch))
                Else
                    collection.Add(enumerator.Current)
                End If
                b = enumerator.MoveNext
            Loop
        End Sub
        
        Public Overridable Function Clone(ByVal deep As Boolean) As car1.BranchCollection
            Dim ret As car1.BranchCollection = New car1.BranchCollection()
            Me.CopyTo(ret, deep)
            Return ret
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Function System_ICloneable_Clone() As Object Implements System.ICloneable.Clone
            Return Me.Clone(true)
        End Function
        
        Public Overridable Sub CancelNew(ByVal index As Integer) Implements System.ComponentModel.ICancelAddNew.CancelNew
            If ((Me._addNewPos >= 0)  _
                        AndAlso (Me._addNewPos = index)) Then
                Me.RemoveAt(index)
                Me._addNewPos = -1
            End If
        End Sub
        
        Public Overridable Sub EndNew(ByVal index As Integer) Implements System.ComponentModel.ICancelAddNew.EndNew
            If ((Me._addNewPos >= 0)  _
                        AndAlso (Me._addNewPos = index)) Then
                Me._addNewPos = -1
            End If
        End Sub
        
        Private Sub AddIndex(ByVal [property] As System.ComponentModel.PropertyDescriptor) Implements System.ComponentModel.IBindingList.AddIndex
            Me._blm2008035919.AddIndex([property])
        End Sub
        
        Protected Overridable Sub OnAddingNew(ByVal e As System.ComponentModel.AddingNewEventArgs)
            If (Not (Me.AddingNewEvent) Is Nothing) Then
                RaiseEvent AddingNew(Me, e)
            End If
        End Sub
        
        Private Function AddNew() As Object Implements System.ComponentModel.IBindingList.AddNew
            Dim add As car1.Branch = New car1.Branch()
            Dim e As System.ComponentModel.AddingNewEventArgs = New System.ComponentModel.AddingNewEventArgs(add)
            Me.OnAddingNew(e)
            add = CType(e.NewObject,car1.Branch)
            If (add Is Nothing) Then
                add = New car1.Branch()
            End If
            add.Name = "AutoNewKey"
            add.Id = 0
            Me._addNewPos = Me.Add(add)
            Return add
        End Function
        
        Private Sub ApplySort(ByVal [property] As System.ComponentModel.PropertyDescriptor, ByVal direction As System.ComponentModel.ListSortDirection) Implements System.ComponentModel.IBindingList.ApplySort
            Me._blm2008035919.ApplySort([property], direction)
        End Sub
        
        Private Function Find(ByVal [property] As System.ComponentModel.PropertyDescriptor, ByVal key As Object) As Integer Implements System.ComponentModel.IBindingList.Find
            Return Me._blm2008035919.Find([property], key)
        End Function
        
        Private Sub RemoveIndex(ByVal [property] As System.ComponentModel.PropertyDescriptor) Implements System.ComponentModel.IBindingList.RemoveIndex
            Me._blm2008035919.RemoveIndex([property])
        End Sub
        
        Private Sub RemoveSort() Implements System.ComponentModel.IBindingList.RemoveSort
            Me._blm2008035919.RemoveSort
        End Sub
        
        Protected Overridable Sub OnListChanged(ByVal e As System.ComponentModel.ListChangedEventArgs)
            If (e Is Nothing) Then
                Throw New System.ArgumentNullException("e")
            End If
            If (Me.RaiseListChangedEvents = false) Then
                Return
            End If
            If (((e.ListChangedType = System.ComponentModel.ListChangedType.Reset)  _
                        = false)  _
                        AndAlso (e.NewIndex < 0)) Then
                Return
            End If
            If (Not (Me.ListChangedEvent) Is Nothing) Then
                RaiseEvent ListChanged(Me, e)
            End If
        End Sub
        
        Public Sub AddRange(ByVal collection As System.Collections.Generic.IEnumerable(Of car1.Branch))
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(Me, collection)
        End Sub
        
        Private Sub OnItemKeyChanged(ByVal sender As Object, ByVal e As CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of String))
            If (e Is Nothing) Then
                Throw New System.ArgumentNullException("e")
            End If
            If (e.OldKey Is Nothing) Then
                Return
            End If
            Dim existing As car1.Branch = Nothing
            If (Me.BaseTable.TryGetValue(e.OldKey, existing) = false) Then
                Return
            End If
            If ((Not (sender) Is Nothing)  _
                        AndAlso (GetType(CodeFluent.Runtime.Utilities.IKeyable(Of String)).IsAssignableFrom(sender.GetType) = true)) Then
                Dim item As CodeFluent.Runtime.Utilities.IKeyable(Of String) = CType(sender,CodeFluent.Runtime.Utilities.IKeyable(Of String))
                Try 
                    Me.BaseTable.Add(item.Key, existing)
                Catch ane As System.ArgumentNullException
                    Throw New System.ArgumentNullException(car1.Resources.Manager.GetUserMessage(Nothing, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "car1.BranchCollection", CType(item,CodeFluent.Runtime.ICodeFluentEntity).EntityKey), ane)
                Catch ae As System.ArgumentException
                    Throw New System.ArgumentException(car1.Resources.Manager.GetUserMessage(Nothing, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "car1.BranchCollection", item.Key), ae)
                End Try
                Me.BaseTable.Remove(e.OldKey)
            End If
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Shared Function PageLoadAll(ByVal pageIndex As Integer, ByVal pageSize As Integer) As car1.BranchCollection
            Return car1.BranchCollection.PageLoadAll(pageIndex, pageSize, Nothing)
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Shared Function PageLoadByCity(ByVal pageIndex As Integer, ByVal pageSize As Integer, ByVal cityId As Integer) As car1.BranchCollection
            Dim city As car1.City = car1.City.Load(cityId)
            If (city Is Nothing) Then
                Return New car1.BranchCollection()
            End If
            Return car1.BranchCollection.PageLoadByCity(pageIndex, pageSize, Nothing, city)
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Shared Function Save(ByVal branch As car1.Branch) As Boolean
            If (branch Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = branch.Save
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Overloads Shared Function Insert(ByVal branch As car1.Branch) As Boolean
            Dim ret As Boolean = car1.Branch.Save(branch)
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Shared Function Delete(ByVal branch As car1.Branch) As Boolean
            If (branch Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = branch.Delete
            Return ret
        End Function
    End Class
End Namespace
