'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace car1
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: Saturday, 12 April 2014 18:46.
    'Build:1.0.61214.0769
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0769"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute(),  _
     System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, SerialNumber={SerialNumber}, id={id}"),  _
     System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.NameTypeConverter))>  _
    Partial Public Class NewCar
        Implements System.ICloneable, System.IComparable, System.IComparable(Of car1.NewCar), CodeFluent.Runtime.ICodeFluentCollectionEntity(Of Integer), System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable(Of car1.NewCar)
        
        Private _raisePropertyChangedEvents As Boolean = true
        
        Private _entityState As CodeFluent.Runtime.CodeFluentEntityState
        
        Private _rowVersion() As Byte
        
        Private _id As Integer = -1
        
        Private _serialNumber As String = CType(Nothing, String)
        
        Private _vehicleType As String = CType(Nothing, String)
        
        Private _vehicleStatus As car1.VehicleStatus = car1.VehicleStatus.Available
        
        Private _desc As String = CType(Nothing, String)
        
        Private _val As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Public Sub New()
            MyBase.New
            Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Overridable Property RaisePropertyChangedEvents() As Boolean
            Get
                Return Me._raisePropertyChangedEvents
            End Get
            Set
                Me._raisePropertyChangedEvents = value
            End Set
        End Property
        
        Public Overridable Property EntityKey() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityKey
            Get
                Return Me.id.ToString
            End Get
            Set
                Me.id = CType(ConvertUtilities.ChangeType(value, GetType(Integer), -1),Integer)
            End Set
        End Property
        
        Public Overridable ReadOnly Property EntityDisplayName() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityDisplayName
            Get
                Return Me.SerialNumber
            End Get
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true),  _
         System.ComponentModel.DataObjectFieldAttribute(false, true),  _
         System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.ByteArrayConverter))>  _
        Public Property RowVersion() As Byte()
            Get
                Return Me._rowVersion
            End Get
            Set
                If ((Not (value) Is Nothing)  _
                            AndAlso (value.Length = 0)) Then
                    value = Nothing
                End If
                Me._rowVersion = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("RowVersion"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(-1,Integer)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer)),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me._id) = true) Then
                    Return
                End If
                Dim oldKey As Integer = Me._id
                Me._id = value
                Try 
                    Me.OnCollectionKeyChanged(oldKey)
                Catch __exception As System.ArgumentException
                    Me._id = oldKey
                    Return
                End Try
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("id"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property SerialNumber() As String
            Get
                Return Me._serialNumber
            End Get
            Set
                Me._serialNumber = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("SerialNumber"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property VehicleType() As String
            Get
                Return Me._vehicleType
            End Get
            Set
                Me._vehicleType = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("VehicleType"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(car1.VehicleStatus))>  _
        Public Property VehicleStatus() As car1.VehicleStatus
            Get
                Return Me._vehicleStatus
            End Get
            Set
                Me._vehicleStatus = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("VehicleStatus"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property Desc() As String
            Get
                Return Me._desc
            End Get
            Set
                Me._desc = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Desc"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property Val() As Double
            Get
                Return Me._val
            End Get
            Set
                Me._val = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Val"))
            End Set
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Error() As String Implements System.ComponentModel.IDataErrorInfo.[Error]
            Get
                Return Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            End Get
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Item(ByVal columnName As String) As String Implements System.ComponentModel.IDataErrorInfo.Item
            Get
                Return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, Me, columnName, Nothing)
            End Get
        End Property
        
        ReadOnly Property CodeFluent_Runtime_Utilities_IKeyable_System_Int32__Key() As Integer Implements CodeFluent.Runtime.Utilities.IKeyable(Of Integer).Key
            Get
                Return Me.id
            End Get
        End Property
        
        Public Overridable Property EntityState() As CodeFluent.Runtime.CodeFluentEntityState Implements CodeFluent.Runtime.ICodeFluentEntity.EntityState
            Get
                Return Me._entityState
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of CodeFluent.Runtime.CodeFluentEntityState).Default.Equals(value, Me.EntityState) = true) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                Me._entityState = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("EntityState"))
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Public Event EntityAction As CodeFluent.Runtime.CodeFluentEntityActionEventHandler Implements CodeFluent.Runtime.ICodeFluentEntity.EntityAction
        
        Public Event KeyChanged As System.EventHandler(Of CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Integer)) Implements CodeFluent.Runtime.Utilities.IKeyable(Of Integer).KeyChanged
        
        Protected Overridable Sub OnPropertyChanged(ByVal e As System.ComponentModel.PropertyChangedEventArgs)
            If (Me.RaisePropertyChangedEvents = false) Then
                Return
            End If
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, e)
            End If
        End Sub
        
        Protected Overridable Sub OnEntityAction(ByVal e As CodeFluent.Runtime.CodeFluentEntityActionEventArgs)
            If (Not (Me.EntityActionEvent) Is Nothing) Then
                RaiseEvent EntityAction(Me, e)
            End If
        End Sub
        
        Public Overloads Overridable Function Equals(ByVal newCar As car1.NewCar) As Boolean Implements System.IEquatable(Of car1.NewCar).Equals
            If (newCar Is Nothing) Then
                Return false
            End If
            If (Me.id = -1) Then
                Return MyBase.Equals(newCar)
            End If
            Return (Me.id.Equals(newCar.id) = true)
        End Function
        
        Public Overloads Overrides Function GetHashCode() As Integer
            Return Me._id
        End Function
        
        Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
            Dim newCar As car1.NewCar = Nothing
            Try 
                newCar = CType(obj,car1.NewCar)
            Catch icex As System.InvalidCastException
                newCar = Nothing
            End Try
            Return Me.Equals(newCar)
        End Function
        
        Overridable Function System_IComparable_CompareTo(ByVal value As Object) As Integer Implements System.IComparable.CompareTo
            Dim newCar As car1.NewCar = Nothing
            Try 
                newCar = CType(value,car1.NewCar)
            Catch icex As System.InvalidCastException
                newCar = Nothing
            End Try
            If (newCar Is Nothing) Then
                Throw New System.ArgumentException("value")
            End If
            Dim localCompareTo As Integer = Me.CompareTo(newCar)
            Return localCompareTo
        End Function
        
        Public Overridable Function CompareTo(ByVal newCar As car1.NewCar) As Integer Implements System.IComparable(Of car1.NewCar).CompareTo
            If (newCar Is Nothing) Then
                Throw New System.ArgumentNullException("newCar")
            End If
            Dim localCompareTo As Integer = Me.id.CompareTo(newCar.id)
            Return localCompareTo
        End Function
        
        Public Overloads Overridable Function Validate(ByVal culture As System.Globalization.CultureInfo) As String
            Return CodeFluentPersistence.Validate(culture, Me, Nothing)
        End Function
        
        Public Overloads Overridable Sub Validate(ByVal culture As System.Globalization.CultureInfo, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentSummaryValidator.Validate
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results)
            evt.Culture = culture
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Dim externalValidate As String
                If (Not (evt.Argument) Is Nothing) Then
                    externalValidate = evt.Argument.ToString
                Else
                    externalValidate = car1.Resources.Manager.GetStringWithDefault(culture, "car1.NewCar.ExternalValidate", "Type 'car1.NewCar' cannot be validated.", Nothing)
                End If
                CodeFluentPersistence.AddValidationError(results, externalValidate)
            End If
            CodeFluentPersistence.ValidateMember(culture, results, Me, Nothing)
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results))
        End Sub
        
        Public Overloads Sub Validate()
            Dim var As String = Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            If (Not (var) Is Nothing) Then
                Throw New CodeFluent.Runtime.CodeFluentValidationException(var)
            End If
        End Sub
        
        Function CodeFluent_Runtime_ICodeFluentValidator_Validate(ByVal culture As System.Globalization.CultureInfo) As String Implements CodeFluent.Runtime.ICodeFluentValidator.Validate
            Dim localValidate As String = Me.Validate(culture)
            Return localValidate
        End Function
        
        Sub CodeFluent_Runtime_ICodeFluentMemberValidator_Validate(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentMemberValidator.Validate
            Me.ValidateMember(culture, memberName, results)
        End Sub
        
        Public Overloads Overridable Function Delete() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Delete
            Dim ret As Boolean = false
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return ret
            End If
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted) Then
                Return ret
            End If
            If (Me.RowVersion Is Nothing) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "NewCar", "Delete")
            persistence.AddParameter("@NewCar_id", Me.id, CType(-1,Integer))
            persistence.AddParameter("@_rowVersion", Me.RowVersion)
            persistence.ExecuteNonQuery
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false))
            ret = true
            Return ret
        End Function
        
        Protected Overridable Sub ReadRecord(ByVal reader As System.Data.IDataReader, ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.Properties)  _
                        = 0)  _
                        = false) Then
                Me._id = CodeFluentPersistence.GetReaderValue(reader, "NewCar_id", CType(-1,Integer))
                Me._serialNumber = CodeFluentPersistence.GetReaderValue(reader, "NewCar_SerialNumber", CType(CType(Nothing, String),String))
                Me._vehicleType = CodeFluentPersistence.GetReaderValue(reader, "NewCar_VehicleType", CType(CType(Nothing, String),String))
                Me._vehicleStatus = CType(CodeFluentPersistence.GetReaderValueEnum(reader, "NewCar_VehicleStatus", CType(car1.VehicleStatus.Available,car1.VehicleStatus)),car1.VehicleStatus)
                Me._desc = CodeFluentPersistence.GetReaderValue(reader, "NewCar_Desc", CType(CType(Nothing, String),String))
                Me._val = CodeFluentPersistence.GetReaderValue(reader, "NewCar_Val", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.RowVersion)  _
                        = 0)  _
                        = false) Then
                Me._rowVersion = CodeFluentPersistence.GetReaderValue(reader, "_rowVersion", CType(Nothing,Byte()))
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecord(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecord
            Me.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
        End Sub
        
        Protected Overridable Sub ReadRecordOnSave(ByVal reader As System.Data.IDataReader)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            Me._id = CodeFluentPersistence.GetReaderValue(reader, "NewCar_id", CType(-1,Integer))
            Me._rowVersion = CodeFluentPersistence.GetReaderValue(reader, "_rowVersion", CType(Nothing,Byte()))
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecordOnSave(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave
            Me.ReadRecordOnSave(reader)
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function Load(ByVal id As Integer) As car1.NewCar
            If (id = -1) Then
                Return Nothing
            End If
            Dim newCar As car1.NewCar = New car1.NewCar()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "NewCar", "Load")
            persistence.AddParameter("@id", id, CType(-1,Integer))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    newCar.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    newCar.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return newCar
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], false)>  _
        Public Shared Function LoadByid(ByVal id As Integer) As car1.NewCar
            If (id = -1) Then
                Return Nothing
            End If
            Dim newCar As car1.NewCar = New car1.NewCar()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "NewCar", "LoadByid")
            persistence.AddParameter("@id", id, CType(-1,Integer))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    newCar.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    newCar.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return newCar
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        Public Overridable Function Reload(ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions) As Boolean
            Dim ret As Boolean = false
            If (Me.id = -1) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "NewCar", "Load")
            persistence.AddParameter("@id", Me.id, CType(-1,Integer))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecord(reader, options)
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    ret = true
                Else
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return ret
        End Function
        
        Protected Overridable Function BaseSave(ByVal force As Boolean) As Boolean
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) Then
                car1.NewCar.Delete(Me)
                Return false
            End If
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return false
            End If
            CodeFluentPersistence.ThrowIfDeleted(Me)
            Me.Validate
            If ((force = false)  _
                        AndAlso (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged)) Then
                Return false
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "NewCar", "Save")
            persistence.AddParameter("@NewCar_id", Me.id, CType(-1,Integer))
            persistence.AddParameter("@NewCar_SerialNumber", Me.SerialNumber, CType(Nothing, String))
            persistence.AddParameter("@NewCar_VehicleType", Me.VehicleType, CType(Nothing, String))
            persistence.AddParameterEnumInt32("@NewCar_VehicleStatus", Me.VehicleStatus, car1.VehicleStatus.Available)
            persistence.AddParameter("@NewCar_Desc", Me.Desc, CType(Nothing, String))
            persistence.AddParameter("@NewCar_Val", Me.Val, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@_trackLastWriteUser", persistence.Context.User.Name)
            persistence.AddParameter("@_rowVersion", Me.RowVersion)
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecordOnSave(reader)
                End If
                CodeFluentPersistence.NextResults(reader)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false))
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
            Return true
        End Function
        
        Public Overloads Overridable Function Save() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Save
            Dim localSave As Boolean = Me.BaseSave(false)
            Return localSave
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Shared Function Save(ByVal newCar As car1.NewCar) As Boolean
            If (newCar Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = newCar.Save
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Shared Function Insert(ByVal newCar As car1.NewCar) As Boolean
            Dim ret As Boolean = car1.NewCar.Save(newCar)
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Shared Function Delete(ByVal newCar As car1.NewCar) As Boolean
            If (newCar Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = newCar.Delete
            Return ret
        End Function
        
        Public Function Trace() As String
            Dim stringBuilder As System.Text.StringBuilder = New System.Text.StringBuilder()
            Dim stringWriter As System.IO.StringWriter = New System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture)
            Dim writer As System.CodeDom.Compiler.IndentedTextWriter = New System.CodeDom.Compiler.IndentedTextWriter(stringWriter)
            Me.BaseTrace(writer)
            writer.Flush
            CType(writer,System.IDisposable).Dispose
            CType(stringWriter,System.IDisposable).Dispose
            Dim sr As String = stringBuilder.ToString
            Return sr
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub CodeFluent_Runtime_ICodeFluentObject_Trace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter) Implements CodeFluent.Runtime.ICodeFluentObject.Trace
            Me.BaseTrace(writer)
        End Sub
        
        Protected Overridable Sub BaseTrace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter)
            writer.Write("[")
            writer.Write("id=")
            writer.Write(Me.id)
            writer.Write(",")
            writer.Write("SerialNumber=")
            writer.Write(Me.SerialNumber)
            writer.Write(",")
            writer.Write("VehicleType=")
            writer.Write(Me.VehicleType)
            writer.Write(",")
            writer.Write("VehicleStatus=")
            writer.Write(Me.VehicleStatus)
            writer.Write(",")
            writer.Write("Desc=")
            writer.Write(Me.Desc)
            writer.Write(",")
            writer.Write("Val=")
            writer.Write(Me.Val)
            writer.Write(", EntityState=")
            writer.Write(Me.EntityState)
            writer.Write("]")
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function LoadByEntityKey(ByVal key As String) As car1.NewCar
            If (key Is String.Empty) Then
                Return Nothing
            End If
            Dim newCar As car1.NewCar
            Dim var As Integer = CType(ConvertUtilities.ChangeType(key, GetType(Integer), -1),Integer)
            newCar = car1.NewCar.Load(var)
            Return newCar
        End Function
        
        Protected Overridable Sub ValidateMember(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException))
        End Sub
        
        Public Overloads Function Clone(ByVal deep As Boolean) As car1.NewCar
            Dim newCar As car1.NewCar = New car1.NewCar()
            Me.CopyTo(newCar, deep)
            Return newCar
        End Function
        
        Public Overloads Function Clone() As car1.NewCar
            Dim localClone As car1.NewCar = Me.Clone(true)
            Return localClone
        End Function
        
        Function System_ICloneable_Clone() As Object Implements System.ICloneable.Clone
            Dim localClone As Object = Me.Clone
            Return localClone
        End Function
        
        Public Overridable Sub CopyFrom(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            If (dict.Contains("id") = true) Then
                Me.id = CType(ConvertUtilities.ChangeType(dict("id"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("Desc") = true) Then
                Me.Desc = CType(ConvertUtilities.ChangeType(dict("Desc"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("Val") = true) Then
                Me.Val = CType(ConvertUtilities.ChangeType(dict("Val"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("VehicleStatus") = true) Then
                Me.VehicleStatus = CType(ConvertUtilities.ChangeType(dict("VehicleStatus"), GetType(car1.VehicleStatus), car1.VehicleStatus.Available),car1.VehicleStatus)
            End If
            If (dict.Contains("SerialNumber") = true) Then
                Me.SerialNumber = CType(ConvertUtilities.ChangeType(dict("SerialNumber"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("VehicleType") = true) Then
                Me.VehicleType = CType(ConvertUtilities.ChangeType(dict("VehicleType"), GetType(String), CType(Nothing, String)),String)
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal newCar As car1.NewCar, ByVal deep As Boolean)
            If (newCar Is Nothing) Then
                Throw New System.ArgumentNullException("newCar")
            End If
            newCar.id = Me.id
            newCar.Desc = Me.Desc
            newCar.Val = Me.Val
            newCar.VehicleStatus = Me.VehicleStatus
            newCar.SerialNumber = Me.SerialNumber
            newCar.VehicleType = Me.VehicleType
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, newCar))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            dict("id") = Me.id
            dict("Desc") = Me.Desc
            dict("Val") = Me.Val
            dict("VehicleStatus") = Me.VehicleStatus
            dict("SerialNumber") = Me.SerialNumber
            dict("VehicleType") = Me.VehicleType
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict))
        End Sub
        
        Protected Sub OnCollectionKeyChanged(ByVal key As Integer)
            If (Not (Me.KeyChangedEvent) Is Nothing) Then
                RaiseEvent KeyChanged(Me, New CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Integer)(key))
            End If
        End Sub
    End Class
End Namespace
