'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace car1
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: Monday, 14 April 2014 09:11.
    'Build:1.0.61214.0769
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0769"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute(),  _
     System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, Id={Id}"),  _
     System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.NameTypeConverter))>  _
    Partial Public Class RentalAgreement
        Implements System.ICloneable, System.IComparable, System.IComparable(Of car1.RentalAgreement), CodeFluent.Runtime.ICodeFluentCollectionEntity(Of Integer), System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable(Of car1.RentalAgreement)
        
        Private _raisePropertyChangedEvents As Boolean = true
        
        Private _entityState As CodeFluent.Runtime.CodeFluentEntityState
        
        Private _rowVersion() As Byte
        
        Private _id As Integer = -1
        
        Private _customerId As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _customer As car1.Customer = Nothing
        
        Private _carId As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _car As car1.Car = Nothing
        
        Private _carOptions As car1.CarOptions = car1.CarOptions.GPS
        
        Private _pickupBranchId As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _pickupBranch As car1.Branch = Nothing
        
        Private _actualReturnBranchId As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _actualReturnBranch As car1.Branch = Nothing
        
        Private _scheduledReturnBranchId As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _scheduledReturnBranch As car1.Branch = Nothing
        
        Private _pickupDate As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _scheduledReturnDate As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _actualReturnDate As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _requestedCarGroupId As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _requestedCarGroup As car1.CarGroup = Nothing
        
        Private _actualCarGroupId As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _actualCarGroup As car1.CarGroup = Nothing
        
        Private _rentalAmount As Single = CodeFluentPersistence.DefaultSingleValue
        
        Private _isAccepted As Boolean = CodeFluentPersistence.DefaultBooleanValue
        
        Private _isAssigned As Boolean = CodeFluentPersistence.DefaultBooleanValue
        
        <System.NonSerializedAttribute()>  _
        Private _offers As car1.OfferCollection
        
        <System.NonSerializedAttribute()>  _
        Private _coverages As car1.CoverageCollection
        
        Private _coverageSubtotalPrice As Single = CodeFluentPersistence.DefaultSingleValue
        
        Private _totalPrice As Single = CodeFluentPersistence.DefaultSingleValue
        
        Private _carGroupId As Integer = -1
        
        <System.NonSerializedAttribute()>  _
        Private _carGroup As car1.CarGroup = Nothing
        
        Private _returnedDate As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _duration As Integer = CodeFluentPersistence.DefaultInt32Value
        
        <System.NonSerializedAttribute()>  _
        Private Shared _swrapper5684426f0257b7a397a3c1dd288b5037 As CodeFluent.Runtime.Rules.RuleWrapper = New CodeFluent.Runtime.Rules.RuleWrapper("CodeFluent.Runtime.Rules.ILog.Method, CodeFluent.Runtime.Rules.ILog", New CodeFluent.Runtime.Utilities.Pair(Of String, Object)("RuleSetTypeName", "CarRentalBizProj, CarRentalBizProj"), New CodeFluent.Runtime.Utilities.Pair(Of String, Object)("CacheKey", "5684426f0257b7a397a3c1dd288b5037"), New CodeFluent.Runtime.Utilities.Pair(Of String, Object)("Name", "car1.RentalAgreement.AgeCheck"), New CodeFluent.Runtime.Utilities.Pair(Of String, Object)("MethodName", "AgeCheck"), New CodeFluent.Runtime.Utilities.Pair(Of String, Object)("BindingFlags", "Instance, Public, InvokeMethod"))
        
        'Snippet method '_snippet3177414175'
Private Sub OnGetCarGroup()
		  _carGroup = IIf(Not ActualCarGroup Is Nothing, ActualCarGroup, RequestedCarGroup)
      End Sub

      Private Sub OnGetReturnedDate()
	      _returnedDate = IIf(ActualReturnDate <> System.DateTime.MinValue, ActualReturnDate, ScheduledReturnDate)
      End Sub

      Private Sub OnGetDuration()
		  _duration = (ReturnedDate - PickupDate).Days
      End Sub
        
        Public Sub New()
            MyBase.New
            Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Overridable Property RaisePropertyChangedEvents() As Boolean
            Get
                Return Me._raisePropertyChangedEvents
            End Get
            Set
                Me._raisePropertyChangedEvents = value
            End Set
        End Property
        
        Public Overridable Property EntityKey() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityKey
            Get
                Return Me.Id.ToString
            End Get
            Set
                Me.Id = CType(ConvertUtilities.ChangeType(value, GetType(Integer), -1),Integer)
            End Set
        End Property
        
        Public Overridable ReadOnly Property EntityDisplayName() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityDisplayName
            Get
                Return Me.Id.ToString
            End Get
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true),  _
         System.ComponentModel.DataObjectFieldAttribute(false, true),  _
         System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.ByteArrayConverter))>  _
        Public Property RowVersion() As Byte()
            Get
                Return Me._rowVersion
            End Get
            Set
                If ((Not (value) Is Nothing)  _
                            AndAlso (value.Length = 0)) Then
                    value = Nothing
                End If
                Me._rowVersion = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("RowVersion"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(-1,Integer)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer)),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property Id() As Integer
            Get
                Return Me._id
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me._id) = true) Then
                    Return
                End If
                Dim oldKey As Integer = Me._id
                Me._id = value
                Try 
                    Me.OnCollectionKeyChanged(oldKey)
                Catch __exception As System.ArgumentException
                    Me._id = oldKey
                    Return
                End Try
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Id"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property CustomerId() As Integer
            Get
                If ((Me._customerId = -1)  _
                            AndAlso (Not (Me._customer) Is Nothing)) Then
                    Me._customerId = Me._customer.Id
                End If
                Return Me._customerId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me.CustomerId) = true) Then
                    Return
                End If
                Me._customer = Nothing
                Me._customerId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Customer"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CustomerId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Customer() As car1.Customer
            Get
                If (Me._customer Is Nothing) Then
                    Me._customer = car1.Customer.Load(Me._customerId)
                End If
                Return Me._customer
            End Get
            Set
                Me._customerId = -1
                Me._customer = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Customer"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CustomerId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property CarId() As Integer
            Get
                If ((Me._carId = -1)  _
                            AndAlso (Not (Me._car) Is Nothing)) Then
                    Me._carId = Me._car.Id
                End If
                Return Me._carId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me.CarId) = true) Then
                    Return
                End If
                Me._car = Nothing
                Me._carId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Car"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CarId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Car() As car1.Car
            Get
                If (Me._car Is Nothing) Then
                    Me._car = car1.Car.Load(Me._carId)
                End If
                Return Me._car
            End Get
            Set
                Me._carId = -1
                Me._car = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Car"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CarId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(car1.CarOptions))>  _
        Public Property CarOptions() As car1.CarOptions
            Get
                Return Me._carOptions
            End Get
            Set
                Me._carOptions = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CarOptions"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property PickupBranchId() As Integer
            Get
                If ((Me._pickupBranchId = -1)  _
                            AndAlso (Not (Me._pickupBranch) Is Nothing)) Then
                    Me._pickupBranchId = Me._pickupBranch.Id
                End If
                Return Me._pickupBranchId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me.PickupBranchId) = true) Then
                    Return
                End If
                Me._pickupBranch = Nothing
                Me._pickupBranchId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("PickupBranch"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("PickupBranchId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PickupBranch() As car1.Branch
            Get
                If (Me._pickupBranch Is Nothing) Then
                    Me._pickupBranch = car1.Branch.Load(Me._pickupBranchId)
                End If
                Return Me._pickupBranch
            End Get
            Set
                Me._pickupBranchId = -1
                Me._pickupBranch = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("PickupBranch"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("PickupBranchId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property ActualReturnBranchId() As Integer
            Get
                If ((Me._actualReturnBranchId = -1)  _
                            AndAlso (Not (Me._actualReturnBranch) Is Nothing)) Then
                    Me._actualReturnBranchId = Me._actualReturnBranch.Id
                End If
                Return Me._actualReturnBranchId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me.ActualReturnBranchId) = true) Then
                    Return
                End If
                Me._actualReturnBranch = Nothing
                Me._actualReturnBranchId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualReturnBranch"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualReturnBranchId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ActualReturnBranch() As car1.Branch
            Get
                If (Me._actualReturnBranch Is Nothing) Then
                    Me._actualReturnBranch = car1.Branch.Load(Me._actualReturnBranchId)
                End If
                Return Me._actualReturnBranch
            End Get
            Set
                Me._actualReturnBranchId = -1
                Me._actualReturnBranch = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualReturnBranch"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualReturnBranchId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property ScheduledReturnBranchId() As Integer
            Get
                If ((Me._scheduledReturnBranchId = -1)  _
                            AndAlso (Not (Me._scheduledReturnBranch) Is Nothing)) Then
                    Me._scheduledReturnBranchId = Me._scheduledReturnBranch.Id
                End If
                Return Me._scheduledReturnBranchId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me.ScheduledReturnBranchId) = true) Then
                    Return
                End If
                Me._scheduledReturnBranch = Nothing
                Me._scheduledReturnBranchId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ScheduledReturnBranch"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ScheduledReturnBranchId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ScheduledReturnBranch() As car1.Branch
            Get
                If (Me._scheduledReturnBranch Is Nothing) Then
                    Me._scheduledReturnBranch = car1.Branch.Load(Me._scheduledReturnBranchId)
                End If
                Return Me._scheduledReturnBranch
            End Get
            Set
                Me._scheduledReturnBranchId = -1
                Me._scheduledReturnBranch = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ScheduledReturnBranch"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ScheduledReturnBranchId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property PickupDate() As Date
            Get
                Return Me._pickupDate
            End Get
            Set
                Me._pickupDate = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("PickupDate"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property ScheduledReturnDate() As Date
            Get
                Return Me._scheduledReturnDate
            End Get
            Set
                Me._scheduledReturnDate = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ScheduledReturnDate"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property ActualReturnDate() As Date
            Get
                Return Me._actualReturnDate
            End Get
            Set
                Me._actualReturnDate = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualReturnDate"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property RequestedCarGroupId() As Integer
            Get
                If ((Me._requestedCarGroupId = -1)  _
                            AndAlso (Not (Me._requestedCarGroup) Is Nothing)) Then
                    Me._requestedCarGroupId = Me._requestedCarGroup.Id
                End If
                Return Me._requestedCarGroupId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me.RequestedCarGroupId) = true) Then
                    Return
                End If
                Me._requestedCarGroup = Nothing
                Me._requestedCarGroupId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("RequestedCarGroup"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("RequestedCarGroupId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RequestedCarGroup() As car1.CarGroup
            Get
                If (Me._requestedCarGroup Is Nothing) Then
                    Me._requestedCarGroup = car1.CarGroup.Load(Me._requestedCarGroupId)
                End If
                Return Me._requestedCarGroup
            End Get
            Set
                Me._requestedCarGroupId = -1
                Me._requestedCarGroup = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("RequestedCarGroup"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("RequestedCarGroupId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property ActualCarGroupId() As Integer
            Get
                If ((Me._actualCarGroupId = -1)  _
                            AndAlso (Not (Me._actualCarGroup) Is Nothing)) Then
                    Me._actualCarGroupId = Me._actualCarGroup.Id
                End If
                Return Me._actualCarGroupId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me.ActualCarGroupId) = true) Then
                    Return
                End If
                Me._actualCarGroup = Nothing
                Me._actualCarGroupId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualCarGroup"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualCarGroupId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ActualCarGroup() As car1.CarGroup
            Get
                If (Me._actualCarGroup Is Nothing) Then
                    Me._actualCarGroup = car1.CarGroup.Load(Me._actualCarGroupId)
                End If
                Return Me._actualCarGroup
            End Get
            Set
                Me._actualCarGroupId = -1
                Me._actualCarGroup = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualCarGroup"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ActualCarGroupId"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultSingleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Single))>  _
        Public Property RentalAmount() As Single
            Get
                Return Me._rentalAmount
            End Get
            Set
                Me._rentalAmount = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("RentalAmount"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultBooleanValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Boolean))>  _
        Public Property IsAccepted() As Boolean
            Get
                Return Me._isAccepted
            End Get
            Set
                Me._isAccepted = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IsAccepted"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultBooleanValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Boolean))>  _
        Public Property IsAssigned() As Boolean
            Get
                Return Me._isAssigned
            End Get
            Set
                Me._isAssigned = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("IsAssigned"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ReadOnly Property Offers() As car1.OfferCollection
            Get
                If (Me._offers Is Nothing) Then
                    If ((Me.Id = -1)  _
                                OrElse (Me.EntityState.Equals(CodeFluent.Runtime.CodeFluentEntityState.Created) = true)) Then
                        Me._offers = New car1.OfferCollection(Nothing, Me)
                        Return Me._offers
                    End If
                    Me._offers = car1.OfferCollection.LoadOffersRentalsByRentalAgreement(Me)
                End If
                Return Me._offers
            End Get
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ReadOnly Property Coverages() As car1.CoverageCollection
            Get
                If (Me._coverages Is Nothing) Then
                    If ((Me.Id = -1)  _
                                OrElse (Me.EntityState.Equals(CodeFluent.Runtime.CodeFluentEntityState.Created) = true)) Then
                        Me._coverages = New car1.CoverageCollection(Me)
                        Return Me._coverages
                    End If
                    Me._coverages = car1.CoverageCollection.LoadCoveragesByRentalAgreement(Me)
                End If
                Return Me._coverages
            End Get
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultSingleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Single))>  _
        Public Property CoverageSubtotalPrice() As Single
            Get
                Return Me._coverageSubtotalPrice
            End Get
            Set
                Me._coverageSubtotalPrice = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CoverageSubtotalPrice"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultSingleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Single))>  _
        Public Property TotalPrice() As Single
            Get
                Return Me._totalPrice
            End Get
            Set
                Me._totalPrice = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("TotalPrice"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property CarGroupId() As Integer
            Get
                If ((Me._carGroupId = -1)  _
                            AndAlso (Not (Me._carGroup) Is Nothing)) Then
                    Me._carGroupId = Me._carGroup.Id
                End If
                Return Me._carGroupId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Integer).Default.Equals(value, Me.CarGroupId) = true) Then
                    Return
                End If
                Me._carGroup = Nothing
                Me._carGroupId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CarGroup"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CarGroupId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CarGroup() As car1.CarGroup
            Get
                If (Me._carGroup Is Nothing) Then
                    Me._carGroup = car1.CarGroup.Load(Me._carGroupId)
                End If
                Return Me._carGroup
            End Get
            Set
                Me._carGroupId = -1
                Me._carGroup = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CarGroup"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("CarGroupId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property ReturnedDate() As Date
            Get
                Return Me._returnedDate
            End Get
            Set
                Me._returnedDate = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ReturnedDate"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property Duration() As Integer
            Get
                Return Me._duration
            End Get
            Set
                Me._duration = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("Duration"))
            End Set
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Error() As String Implements System.ComponentModel.IDataErrorInfo.[Error]
            Get
                Return Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            End Get
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Item(ByVal columnName As String) As String Implements System.ComponentModel.IDataErrorInfo.Item
            Get
                Return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, Me, columnName, Nothing)
            End Get
        End Property
        
        ReadOnly Property CodeFluent_Runtime_Utilities_IKeyable_System_Int32__Key() As Integer Implements CodeFluent.Runtime.Utilities.IKeyable(Of Integer).Key
            Get
                Return Me.Id
            End Get
        End Property
        
        Public Overridable Property EntityState() As CodeFluent.Runtime.CodeFluentEntityState Implements CodeFluent.Runtime.ICodeFluentEntity.EntityState
            Get
                Return Me._entityState
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of CodeFluent.Runtime.CodeFluentEntityState).Default.Equals(value, Me.EntityState) = true) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                Me._entityState = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("EntityState"))
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Public Event EntityAction As CodeFluent.Runtime.CodeFluentEntityActionEventHandler Implements CodeFluent.Runtime.ICodeFluentEntity.EntityAction
        
        Public Event KeyChanged As System.EventHandler(Of CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Integer)) Implements CodeFluent.Runtime.Utilities.IKeyable(Of Integer).KeyChanged
        
        Protected Overridable Sub OnPropertyChanged(ByVal e As System.ComponentModel.PropertyChangedEventArgs)
            If (Me.RaisePropertyChangedEvents = false) Then
                Return
            End If
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, e)
            End If
        End Sub
        
        Protected Overridable Sub OnEntityAction(ByVal e As CodeFluent.Runtime.CodeFluentEntityActionEventArgs)
            If (Not (Me.EntityActionEvent) Is Nothing) Then
                RaiseEvent EntityAction(Me, e)
            End If
        End Sub
        
        Public Overloads Overridable Function Equals(ByVal rentalAgreement As car1.RentalAgreement) As Boolean Implements System.IEquatable(Of car1.RentalAgreement).Equals
            If (rentalAgreement Is Nothing) Then
                Return false
            End If
            If (Me.Id = -1) Then
                Return MyBase.Equals(rentalAgreement)
            End If
            Return (Me.Id.Equals(rentalAgreement.Id) = true)
        End Function
        
        Public Overloads Overrides Function GetHashCode() As Integer
            Return Me._id
        End Function
        
        Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
            Dim rentalAgreement As car1.RentalAgreement = Nothing
            Try 
                rentalAgreement = CType(obj,car1.RentalAgreement)
            Catch icex As System.InvalidCastException
                rentalAgreement = Nothing
            End Try
            Return Me.Equals(rentalAgreement)
        End Function
        
        Friend Sub SaveOffersRelations()
            If (Me._offers Is Nothing) Then
                Return
            End If
            Dim enumerator As System.Collections.IEnumerator = CType(Me._offers,CodeFluent.Runtime.ICodeFluentSet).Relations.GetEnumerator
            Dim b As Boolean
            b = enumerator.MoveNext
            Do While b
                Dim entry As System.Collections.DictionaryEntry = CType(enumerator.Current,System.Collections.DictionaryEntry)
                Dim offer As car1.Offer = CType(entry.Key,car1.Offer)
                Dim relationType As CodeFluent.Runtime.CodeFluentRelationType = CType(entry.Value,CodeFluent.Runtime.CodeFluentRelationType)
                If ((relationType = CodeFluent.Runtime.CodeFluentRelationType.Added)  _
                            AndAlso ((offer.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeUnlinked)  _
                            = false)) Then
                    Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
                    persistence.CreateStoredProcedureCommand(Nothing, "RentalAgreement", "SaveOfferRentals")
                    persistence.AddParameter("@Offer_Id", offer.Id, CType(-1,Integer))
                    persistence.AddParameter("@RentalAgreement_Id", Me.Id, CType(-1,Integer))
                    persistence.ExecuteNonQuery
                Else
                    Dim persistence1 As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
                    persistence1.CreateStoredProcedureCommand(Nothing, "RentalAgreement", "DeleteOfferRentals")
                    persistence1.AddParameter("@Offer_Id", offer.Id, CType(-1,Integer))
                    persistence1.AddParameter("@RentalAgreement_Id", Me.Id, CType(-1,Integer))
                    persistence1.ExecuteNonQuery
                End If
                If (offer.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeUnlinked) Then
                    offer.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                End If
                b = enumerator.MoveNext
            Loop
            CType(Me._offers,CodeFluent.Runtime.ICodeFluentSet).Relations.Clear
        End Sub
        
        Friend Sub SaveCoveragesRelations()
            If (Me._coverages Is Nothing) Then
                Return
            End If
            Dim enumerator As System.Collections.IEnumerator = CType(Me._coverages,CodeFluent.Runtime.ICodeFluentSet).Relations.GetEnumerator
            Dim b As Boolean
            b = enumerator.MoveNext
            Do While b
                Dim entry As System.Collections.DictionaryEntry = CType(enumerator.Current,System.Collections.DictionaryEntry)
                Dim coverage As car1.Coverage = CType(entry.Key,car1.Coverage)
                Dim relationType As CodeFluent.Runtime.CodeFluentRelationType = CType(entry.Value,CodeFluent.Runtime.CodeFluentRelationType)
                If ((relationType = CodeFluent.Runtime.CodeFluentRelationType.Added)  _
                            AndAlso ((coverage.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeUnlinked)  _
                            = false)) Then
                    Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
                    persistence.CreateStoredProcedureCommand(Nothing, "Coverage", "SaveRentalAgreementCoverages")
                    persistence.AddParameter("@RentalAgreement_Id", Me.Id, CType(-1,Integer))
                    persistence.AddParameter("@Coverage_Id", coverage.Id, CType(-1,Integer))
                    persistence.ExecuteNonQuery
                Else
                    Dim persistence1 As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
                    persistence1.CreateStoredProcedureCommand(Nothing, "Coverage", "DeleteRentalAgreementCoverages")
                    persistence1.AddParameter("@RentalAgreement_Id", Me.Id, CType(-1,Integer))
                    persistence1.AddParameter("@Coverage_Id", coverage.Id, CType(-1,Integer))
                    persistence1.ExecuteNonQuery
                End If
                If (coverage.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeUnlinked) Then
                    coverage.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                End If
                b = enumerator.MoveNext
            Loop
            CType(Me._coverages,CodeFluent.Runtime.ICodeFluentSet).Relations.Clear
        End Sub
        
        Overridable Function System_IComparable_CompareTo(ByVal value As Object) As Integer Implements System.IComparable.CompareTo
            Dim rentalAgreement As car1.RentalAgreement = Nothing
            Try 
                rentalAgreement = CType(value,car1.RentalAgreement)
            Catch icex As System.InvalidCastException
                rentalAgreement = Nothing
            End Try
            If (rentalAgreement Is Nothing) Then
                Throw New System.ArgumentException("value")
            End If
            Dim localCompareTo As Integer = Me.CompareTo(rentalAgreement)
            Return localCompareTo
        End Function
        
        Public Overridable Function CompareTo(ByVal rentalAgreement As car1.RentalAgreement) As Integer Implements System.IComparable(Of car1.RentalAgreement).CompareTo
            If (rentalAgreement Is Nothing) Then
                Throw New System.ArgumentNullException("rentalAgreement")
            End If
            Dim localCompareTo As Integer = Me.Id.CompareTo(rentalAgreement.Id)
            Return localCompareTo
        End Function
        
        Public Overloads Overridable Function Validate(ByVal culture As System.Globalization.CultureInfo) As String
            Return CodeFluentPersistence.Validate(culture, Me, Nothing)
        End Function
        
        Public Overloads Overridable Sub Validate(ByVal culture As System.Globalization.CultureInfo, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentSummaryValidator.Validate
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results)
            evt.Culture = culture
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Dim externalValidate As String
                If (Not (evt.Argument) Is Nothing) Then
                    externalValidate = evt.Argument.ToString
                Else
                    externalValidate = car1.Resources.Manager.GetStringWithDefault(culture, "car1.RentalAgreement.ExternalValidate", "Type 'car1.RentalAgreement' cannot be validated.", Nothing)
                End If
                CodeFluentPersistence.AddValidationError(results, externalValidate)
            End If
            CodeFluentPersistence.ValidateMember(culture, results, Me, Nothing)
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results))
        End Sub
        
        Public Overloads Sub Validate()
            Dim var As String = Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            If (Not (var) Is Nothing) Then
                Throw New CodeFluent.Runtime.CodeFluentValidationException(var)
            End If
        End Sub
        
        Function CodeFluent_Runtime_ICodeFluentValidator_Validate(ByVal culture As System.Globalization.CultureInfo) As String Implements CodeFluent.Runtime.ICodeFluentValidator.Validate
            Dim localValidate As String = Me.Validate(culture)
            Return localValidate
        End Function
        
        Sub CodeFluent_Runtime_ICodeFluentMemberValidator_Validate(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentMemberValidator.Validate
            Me.ValidateMember(culture, memberName, results)
        End Sub
        
        Public Overloads Overridable Function Delete() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Delete
            Dim ret As Boolean = false
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return ret
            End If
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted) Then
                Return ret
            End If
            If (Me.RowVersion Is Nothing) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "RentalAgreement", "Delete")
            persistence.AddParameter("@RentalAgreement_Id", Me.Id, CType(-1,Integer))
            persistence.AddParameter("@_rowVersion", Me.RowVersion)
            persistence.ExecuteNonQuery
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false))
            ret = true
            Return ret
        End Function
        
        Protected Overridable Sub ReadRecord(ByVal reader As System.Data.IDataReader, ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.Properties)  _
                        = 0)  _
                        = false) Then
                Me._id = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_Id", CType(-1,Integer))
                Me.CustomerId = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_Customer_Id", CType(-1,Integer))
                Me.CarId = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_Car_Id", CType(-1,Integer))
                Me._carOptions = CType(CodeFluentPersistence.GetReaderValueEnum(reader, "RentalAgreement_CarOptions", CType(car1.CarOptions.GPS,car1.CarOptions)),car1.CarOptions)
                Me.PickupBranchId = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_PickupBranch_Id", CType(-1,Integer))
                Me.ActualReturnBranchId = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_ActualReturnBranch_Id", CType(-1,Integer))
                Me.ScheduledReturnBranchId = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_ScheduledReturnBranch_Id", CType(-1,Integer))
                Me._pickupDate = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_PickupDate", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me._scheduledReturnDate = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_ScheduledReturnDate", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me._actualReturnDate = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_ActualReturnDate", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me.RequestedCarGroupId = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_RequestedCarGroup_Id", CType(-1,Integer))
                Me.ActualCarGroupId = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_ActualCarGroup_Id", CType(-1,Integer))
                Me._rentalAmount = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_RentalAmount", CType(CodeFluentPersistence.DefaultSingleValue,Single))
                Me._isAccepted = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_IsAccepted", CType(CodeFluentPersistence.DefaultBooleanValue,Boolean))
                Me._isAssigned = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_IsAssigned", CType(CodeFluentPersistence.DefaultBooleanValue,Boolean))
                Me._coverageSubtotalPrice = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_CoverageSubtotalPrice", CType(CodeFluentPersistence.DefaultSingleValue,Single))
                Me._totalPrice = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_TotalPrice", CType(CodeFluentPersistence.DefaultSingleValue,Single))
                Me.CarGroupId = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_CarGroup_Id", CType(-1,Integer))
                Me._returnedDate = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_ReturnedDate", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me._duration = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_Duration", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.RowVersion)  _
                        = 0)  _
                        = false) Then
                Me._rowVersion = CodeFluentPersistence.GetReaderValue(reader, "_rowVersion", CType(Nothing,Byte()))
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecord(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecord
            Me.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
        End Sub
        
        Protected Overridable Sub ReadRecordOnSave(ByVal reader As System.Data.IDataReader)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            Me._id = CodeFluentPersistence.GetReaderValue(reader, "RentalAgreement_Id", CType(-1,Integer))
            Me._rowVersion = CodeFluentPersistence.GetReaderValue(reader, "_rowVersion", CType(Nothing,Byte()))
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecordOnSave(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave
            Me.ReadRecordOnSave(reader)
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function Load(ByVal id As Integer) As car1.RentalAgreement
            If (id = -1) Then
                Return Nothing
            End If
            Dim rentalAgreement As car1.RentalAgreement = New car1.RentalAgreement()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "RentalAgreement", "Load")
            persistence.AddParameter("@Id", id, CType(-1,Integer))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    rentalAgreement.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    rentalAgreement.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return rentalAgreement
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], false)>  _
        Public Shared Function LoadById(ByVal id As Integer) As car1.RentalAgreement
            If (id = -1) Then
                Return Nothing
            End If
            Dim rentalAgreement As car1.RentalAgreement = New car1.RentalAgreement()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "RentalAgreement", "LoadById")
            persistence.AddParameter("@Id", id, CType(-1,Integer))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    rentalAgreement.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    rentalAgreement.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return rentalAgreement
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        Public Overridable Function AgeCheck(ByVal customer As car1.Customer) As Integer
            Dim arguments As System.Collections.Specialized.OrderedDictionary = New System.Collections.Specialized.OrderedDictionary(System.StringComparer.CurrentCultureIgnoreCase)
            arguments.Add("RentalAgreement", Me)
            arguments.Add("Customer", customer)
            Dim ret As Integer
            ret = CType(car1.RentalAgreement._swrapper5684426f0257b7a397a3c1dd288b5037.Invoke(arguments, GetType(Integer), Nothing, CodeFluentPersistence.DefaultInt32Value),Integer)
            Return ret
        End Function
        
        Public Overridable Function Reload(ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions) As Boolean
            Dim ret As Boolean = false
            If (Me.Id = -1) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "RentalAgreement", "Load")
            persistence.AddParameter("@Id", Me.Id, CType(-1,Integer))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecord(reader, options)
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    ret = true
                Else
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return ret
        End Function
        
        Protected Overridable Function BaseSave(ByVal force As Boolean) As Boolean
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) Then
                car1.RentalAgreement.Delete(Me)
                Return false
            End If
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return false
            End If
            CodeFluentPersistence.ThrowIfDeleted(Me)
            Me.Validate
            If ((force = false)  _
                        AndAlso (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged)) Then
                Return false
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(car1.Constants.car1StoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "RentalAgreement", "Save")
            persistence.AddParameter("@RentalAgreement_Id", Me.Id, CType(-1,Integer))
            persistence.AddParameter("@RentalAgreement_Customer_Id", Me.CustomerId, CType(-1,Integer))
            persistence.AddParameter("@RentalAgreement_Car_Id", Me.CarId, CType(-1,Integer))
            persistence.AddRawParameterEnumInt32("@RentalAgreement_CarOptions", Me.CarOptions)
            persistence.AddParameter("@RentalAgreement_PickupBranch_Id", Me.PickupBranchId, CType(-1,Integer))
            persistence.AddParameter("@RentalAgreement_ActualReturnBranch_Id", Me.ActualReturnBranchId, CType(-1,Integer))
            persistence.AddParameter("@RentalAgreement_ScheduledReturnBranch_Id", Me.ScheduledReturnBranchId, CType(-1,Integer))
            persistence.AddParameter("@RentalAgreement_PickupDate", Me.PickupDate, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@RentalAgreement_ScheduledReturnDate", Me.ScheduledReturnDate, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@RentalAgreement_ActualReturnDate", Me.ActualReturnDate, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@RentalAgreement_RequestedCarGroup_Id", Me.RequestedCarGroupId, CType(-1,Integer))
            persistence.AddParameter("@RentalAgreement_ActualCarGroup_Id", Me.ActualCarGroupId, CType(-1,Integer))
            persistence.AddParameter("@RentalAgreement_RentalAmount", Me.RentalAmount, CodeFluentPersistence.DefaultSingleValue)
            persistence.AddRawParameter("@RentalAgreement_IsAccepted", Me.IsAccepted)
            persistence.AddRawParameter("@RentalAgreement_IsAssigned", Me.IsAssigned)
            persistence.AddParameter("@RentalAgreement_CoverageSubtotalPrice", Me.CoverageSubtotalPrice, CodeFluentPersistence.DefaultSingleValue)
            persistence.AddParameter("@RentalAgreement_TotalPrice", Me.TotalPrice, CodeFluentPersistence.DefaultSingleValue)
            persistence.AddParameter("@RentalAgreement_CarGroup_Id", Me.CarGroupId, CType(-1,Integer))
            persistence.AddParameter("@RentalAgreement_ReturnedDate", Me.ReturnedDate, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@RentalAgreement_Duration", Me.Duration, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@_trackLastWriteUser", persistence.Context.User.Name)
            persistence.AddParameter("@_rowVersion", Me.RowVersion)
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecordOnSave(reader)
                End If
                CodeFluentPersistence.NextResults(reader)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Me.SaveOffersRelations
            Me.SaveCoveragesRelations
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false))
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
            Return true
        End Function
        
        Public Overloads Overridable Function Save() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Save
            Dim localSave As Boolean = Me.BaseSave(false)
            Return localSave
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Shared Function Save(ByVal rentalAgreement As car1.RentalAgreement) As Boolean
            If (rentalAgreement Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = rentalAgreement.Save
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Shared Function Insert(ByVal rentalAgreement As car1.RentalAgreement) As Boolean
            Dim ret As Boolean = car1.RentalAgreement.Save(rentalAgreement)
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Shared Function Delete(ByVal rentalAgreement As car1.RentalAgreement) As Boolean
            If (rentalAgreement Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = rentalAgreement.Delete
            Return ret
        End Function
        
        Public Function Trace() As String
            Dim stringBuilder As System.Text.StringBuilder = New System.Text.StringBuilder()
            Dim stringWriter As System.IO.StringWriter = New System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture)
            Dim writer As System.CodeDom.Compiler.IndentedTextWriter = New System.CodeDom.Compiler.IndentedTextWriter(stringWriter)
            Me.BaseTrace(writer)
            writer.Flush
            CType(writer,System.IDisposable).Dispose
            CType(stringWriter,System.IDisposable).Dispose
            Dim sr As String = stringBuilder.ToString
            Return sr
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub CodeFluent_Runtime_ICodeFluentObject_Trace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter) Implements CodeFluent.Runtime.ICodeFluentObject.Trace
            Me.BaseTrace(writer)
        End Sub
        
        Protected Overridable Sub BaseTrace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter)
            writer.Write("[")
            writer.Write("Id=")
            writer.Write(Me.Id)
            writer.Write(",")
            writer.Write("Customer=")
            If (Not (Me._customer) Is Nothing) Then
                CType(Me._customer,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_customerId=")
            writer.Write(Me._customerId)
            writer.Write(",")
            writer.Write("Car=")
            If (Not (Me._car) Is Nothing) Then
                CType(Me._car,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_carId=")
            writer.Write(Me._carId)
            writer.Write(",")
            writer.Write("CarOptions=")
            writer.Write(Me.CarOptions)
            writer.Write(",")
            writer.Write("PickupBranch=")
            If (Not (Me._pickupBranch) Is Nothing) Then
                CType(Me._pickupBranch,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_pickupBranchId=")
            writer.Write(Me._pickupBranchId)
            writer.Write(",")
            writer.Write("ActualReturnBranch=")
            If (Not (Me._actualReturnBranch) Is Nothing) Then
                CType(Me._actualReturnBranch,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_actualReturnBranchId=")
            writer.Write(Me._actualReturnBranchId)
            writer.Write(",")
            writer.Write("ScheduledReturnBranch=")
            If (Not (Me._scheduledReturnBranch) Is Nothing) Then
                CType(Me._scheduledReturnBranch,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_scheduledReturnBranchId=")
            writer.Write(Me._scheduledReturnBranchId)
            writer.Write(",")
            writer.Write("PickupDate=")
            writer.Write(Me.PickupDate)
            writer.Write(",")
            writer.Write("ScheduledReturnDate=")
            writer.Write(Me.ScheduledReturnDate)
            writer.Write(",")
            writer.Write("ActualReturnDate=")
            writer.Write(Me.ActualReturnDate)
            writer.Write(",")
            writer.Write("RequestedCarGroup=")
            If (Not (Me._requestedCarGroup) Is Nothing) Then
                CType(Me._requestedCarGroup,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_requestedCarGroupId=")
            writer.Write(Me._requestedCarGroupId)
            writer.Write(",")
            writer.Write("ActualCarGroup=")
            If (Not (Me._actualCarGroup) Is Nothing) Then
                CType(Me._actualCarGroup,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_actualCarGroupId=")
            writer.Write(Me._actualCarGroupId)
            writer.Write(",")
            writer.Write("RentalAmount=")
            writer.Write(Me.RentalAmount)
            writer.Write(",")
            writer.Write("IsAccepted=")
            writer.Write(Me.IsAccepted)
            writer.Write(",")
            writer.Write("IsAssigned=")
            writer.Write(Me.IsAssigned)
            writer.Write(",")
            writer.Write("Offers=")
            If (Not (Me._offers) Is Nothing) Then
                CType(Me._offers,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("Coverages=")
            If (Not (Me._coverages) Is Nothing) Then
                CType(Me._coverages,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("CoverageSubtotalPrice=")
            writer.Write(Me.CoverageSubtotalPrice)
            writer.Write(",")
            writer.Write("TotalPrice=")
            writer.Write(Me.TotalPrice)
            writer.Write(",")
            writer.Write("CarGroup=")
            If (Not (Me._carGroup) Is Nothing) Then
                CType(Me._carGroup,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_carGroupId=")
            writer.Write(Me._carGroupId)
            writer.Write(",")
            writer.Write("ReturnedDate=")
            writer.Write(Me.ReturnedDate)
            writer.Write(",")
            writer.Write("Duration=")
            writer.Write(Me.Duration)
            writer.Write(", EntityState=")
            writer.Write(Me.EntityState)
            writer.Write("]")
        End Sub
        
        Public Overloads Overridable Sub SetOffers(ByVal values As System.Collections.IDictionary)
            If (values Is Nothing) Then
                Throw New System.ArgumentNullException("values")
            End If
            Me.Offers.Clear
            Dim enumerator As System.Collections.IEnumerator = values.GetEnumerator
            Dim b As Boolean
            b = enumerator.MoveNext
            Do While b
                Dim entry As System.Collections.DictionaryEntry = CType(enumerator.Current,System.Collections.DictionaryEntry)
                If (Not (entry.Key) Is Nothing) Then
                    Me.Offers.AddByEntityKey(entry.Key.ToString)
                End If
                b = enumerator.MoveNext
            Loop
        End Sub
        
        Public Overloads Overridable Sub SetOffers(ByVal values As Object)
            If (values Is Nothing) Then
                Return
            End If
            Dim dictionary As System.Collections.IDictionary = Nothing
            Try 
                dictionary = CType(values,System.Collections.IDictionary)
            Catch icex As System.InvalidCastException
                dictionary = Nothing
            End Try
            If (Not (dictionary) Is Nothing) Then
                Me.SetOffers(dictionary)
                Return
            End If
            Dim offers As car1.OfferCollection = Nothing
            Try 
                offers = CType(values,car1.OfferCollection)
            Catch icex1 As System.InvalidCastException
                offers = Nothing
            End Try
            If (Not (offers) Is Nothing) Then
                Me._offers = offers
                Return
            End If
        End Sub
        
        Public Overloads Overridable Sub SetCoverages(ByVal values As System.Collections.IDictionary)
            If (values Is Nothing) Then
                Throw New System.ArgumentNullException("values")
            End If
            Me.Coverages.Clear
            Dim enumerator As System.Collections.IEnumerator = values.GetEnumerator
            Dim b As Boolean
            b = enumerator.MoveNext
            Do While b
                Dim entry As System.Collections.DictionaryEntry = CType(enumerator.Current,System.Collections.DictionaryEntry)
                If (Not (entry.Key) Is Nothing) Then
                    Me.Coverages.AddByEntityKey(entry.Key.ToString)
                End If
                b = enumerator.MoveNext
            Loop
        End Sub
        
        Public Overloads Overridable Sub SetCoverages(ByVal values As Object)
            If (values Is Nothing) Then
                Return
            End If
            Dim dictionary As System.Collections.IDictionary = Nothing
            Try 
                dictionary = CType(values,System.Collections.IDictionary)
            Catch icex As System.InvalidCastException
                dictionary = Nothing
            End Try
            If (Not (dictionary) Is Nothing) Then
                Me.SetCoverages(dictionary)
                Return
            End If
            Dim coverages As car1.CoverageCollection = Nothing
            Try 
                coverages = CType(values,car1.CoverageCollection)
            Catch icex1 As System.InvalidCastException
                coverages = Nothing
            End Try
            If (Not (coverages) Is Nothing) Then
                Me._coverages = coverages
                Return
            End If
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function LoadByEntityKey(ByVal key As String) As car1.RentalAgreement
            If (key Is String.Empty) Then
                Return Nothing
            End If
            Dim rentalAgreement As car1.RentalAgreement
            Dim var As Integer = CType(ConvertUtilities.ChangeType(key, GetType(Integer), -1),Integer)
            rentalAgreement = car1.RentalAgreement.Load(var)
            Return rentalAgreement
        End Function
        
        Protected Overridable Sub ValidateMember(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException))
        End Sub
        
        Public Overloads Function Clone(ByVal deep As Boolean) As car1.RentalAgreement
            Dim rentalAgreement As car1.RentalAgreement = New car1.RentalAgreement()
            Me.CopyTo(rentalAgreement, deep)
            Return rentalAgreement
        End Function
        
        Public Overloads Function Clone() As car1.RentalAgreement
            Dim localClone As car1.RentalAgreement = Me.Clone(true)
            Return localClone
        End Function
        
        Function System_ICloneable_Clone() As Object Implements System.ICloneable.Clone
            Dim localClone As Object = Me.Clone
            Return localClone
        End Function
        
        Public Overridable Sub CopyFrom(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            If (dict.Contains("Id") = true) Then
                Me.Id = CType(ConvertUtilities.ChangeType(dict("Id"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("RentalAmount") = true) Then
                Me.RentalAmount = CType(ConvertUtilities.ChangeType(dict("RentalAmount"), GetType(Single), CodeFluentPersistence.DefaultSingleValue),Single)
            End If
            If (dict.Contains("IsAccepted") = true) Then
                Me.IsAccepted = CType(ConvertUtilities.ChangeType(dict("IsAccepted"), GetType(Boolean), CodeFluentPersistence.DefaultBooleanValue),Boolean)
            End If
            If (dict.Contains("ActualReturnDate") = true) Then
                Me.ActualReturnDate = CType(ConvertUtilities.ChangeType(dict("ActualReturnDate"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("Duration") = true) Then
                Me.Duration = CType(ConvertUtilities.ChangeType(dict("Duration"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("TotalPrice") = true) Then
                Me.TotalPrice = CType(ConvertUtilities.ChangeType(dict("TotalPrice"), GetType(Single), CodeFluentPersistence.DefaultSingleValue),Single)
            End If
            If (dict.Contains("ReturnedDate") = true) Then
                Me.ReturnedDate = CType(ConvertUtilities.ChangeType(dict("ReturnedDate"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("IsAssigned") = true) Then
                Me.IsAssigned = CType(ConvertUtilities.ChangeType(dict("IsAssigned"), GetType(Boolean), CodeFluentPersistence.DefaultBooleanValue),Boolean)
            End If
            If (dict.Contains("CoverageSubtotalPrice") = true) Then
                Me.CoverageSubtotalPrice = CType(ConvertUtilities.ChangeType(dict("CoverageSubtotalPrice"), GetType(Single), CodeFluentPersistence.DefaultSingleValue),Single)
            End If
            If (dict.Contains("CarOptions") = true) Then
                Me.CarOptions = CType(ConvertUtilities.ChangeType(dict("CarOptions"), GetType(car1.CarOptions), car1.CarOptions.GPS),car1.CarOptions)
            End If
            If (dict.Contains("PickupDate") = true) Then
                Me.PickupDate = CType(ConvertUtilities.ChangeType(dict("PickupDate"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("ScheduledReturnDate") = true) Then
                Me.ScheduledReturnDate = CType(ConvertUtilities.ChangeType(dict("ScheduledReturnDate"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("CustomerId") = true) Then
                Me.CustomerId = CType(ConvertUtilities.ChangeType(dict("CustomerId"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("CarId") = true) Then
                Me.CarId = CType(ConvertUtilities.ChangeType(dict("CarId"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("CarGroupId") = true) Then
                Me.CarGroupId = CType(ConvertUtilities.ChangeType(dict("CarGroupId"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("RequestedCarGroupId") = true) Then
                Me.RequestedCarGroupId = CType(ConvertUtilities.ChangeType(dict("RequestedCarGroupId"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("ActualCarGroupId") = true) Then
                Me.ActualCarGroupId = CType(ConvertUtilities.ChangeType(dict("ActualCarGroupId"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("ScheduledReturnBranchId") = true) Then
                Me.ScheduledReturnBranchId = CType(ConvertUtilities.ChangeType(dict("ScheduledReturnBranchId"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("ActualReturnBranchId") = true) Then
                Me.ActualReturnBranchId = CType(ConvertUtilities.ChangeType(dict("ActualReturnBranchId"), GetType(Integer), -1),Integer)
            End If
            If (dict.Contains("PickupBranchId") = true) Then
                Me.PickupBranchId = CType(ConvertUtilities.ChangeType(dict("PickupBranchId"), GetType(Integer), -1),Integer)
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal rentalAgreement As car1.RentalAgreement, ByVal deep As Boolean)
            If (rentalAgreement Is Nothing) Then
                Throw New System.ArgumentNullException("rentalAgreement")
            End If
            rentalAgreement.Id = Me.Id
            rentalAgreement.RentalAmount = Me.RentalAmount
            rentalAgreement.IsAccepted = Me.IsAccepted
            rentalAgreement.ActualReturnDate = Me.ActualReturnDate
            rentalAgreement.Duration = Me.Duration
            rentalAgreement.TotalPrice = Me.TotalPrice
            rentalAgreement.ReturnedDate = Me.ReturnedDate
            rentalAgreement.IsAssigned = Me.IsAssigned
            rentalAgreement.CoverageSubtotalPrice = Me.CoverageSubtotalPrice
            rentalAgreement.CarOptions = Me.CarOptions
            rentalAgreement.PickupDate = Me.PickupDate
            rentalAgreement.ScheduledReturnDate = Me.ScheduledReturnDate
            rentalAgreement.CustomerId = Me.CustomerId
            rentalAgreement.CarId = Me.CarId
            rentalAgreement.CarGroupId = Me.CarGroupId
            rentalAgreement.RequestedCarGroupId = Me.RequestedCarGroupId
            rentalAgreement.ActualCarGroupId = Me.ActualCarGroupId
            rentalAgreement.ScheduledReturnBranchId = Me.ScheduledReturnBranchId
            rentalAgreement.ActualReturnBranchId = Me.ActualReturnBranchId
            rentalAgreement.PickupBranchId = Me.PickupBranchId
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, rentalAgreement))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            dict("Id") = Me.Id
            dict("RentalAmount") = Me.RentalAmount
            dict("IsAccepted") = Me.IsAccepted
            dict("ActualReturnDate") = Me.ActualReturnDate
            dict("Duration") = Me.Duration
            dict("TotalPrice") = Me.TotalPrice
            dict("ReturnedDate") = Me.ReturnedDate
            dict("IsAssigned") = Me.IsAssigned
            dict("CoverageSubtotalPrice") = Me.CoverageSubtotalPrice
            dict("CarOptions") = Me.CarOptions
            dict("PickupDate") = Me.PickupDate
            dict("ScheduledReturnDate") = Me.ScheduledReturnDate
            dict("CustomerId") = Me.CustomerId
            dict("CarId") = Me.CarId
            dict("CarGroupId") = Me.CarGroupId
            dict("RequestedCarGroupId") = Me.RequestedCarGroupId
            dict("ActualCarGroupId") = Me.ActualCarGroupId
            dict("ScheduledReturnBranchId") = Me.ScheduledReturnBranchId
            dict("ActualReturnBranchId") = Me.ActualReturnBranchId
            dict("PickupBranchId") = Me.PickupBranchId
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict))
        End Sub
        
        Protected Sub OnCollectionKeyChanged(ByVal key As Integer)
            If (Not (Me.KeyChangedEvent) Is Nothing) Then
                RaiseEvent KeyChanged(Me, New CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Integer)(key))
            End If
        End Sub
    End Class
End Namespace
